# site settings

title: Varad Tote
description: Portfolio and Blog for Varad
taglong: Fullstack MERN Developer
tagshort: Varad's site
url: https://varadtote.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/varadtote/varadtote.github.io

# author settings

author:
  name: Varad Tote
  email: varadtote1412@gmail.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  github: https://github.com/varadtote
  linkedin: https://www.linkedin.com/in/varad-tote-206789167/
  twitter: https://twitter.com/ToteVarad

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
